/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.JTable;
/**
 *
 * @author magar
 */
public class Catalogo extends javax.swing.JFrame {
    private int k;
    public static float total=0;
    /**
     * Creates new form Catalogo
     */
    public Catalogo() {
        initComponents();
        this.setLocationRelativeTo(null);
        k=0;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TCatalogo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TFProducto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ButtonConsultar = new javax.swing.JButton();
        ButtonListo = new javax.swing.JButton();
        CreditoRB = new javax.swing.JRadioButton();
        ContadoRB = new javax.swing.JRadioButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID del Articulo", "Modelo", "Serie", "Descripcion", "Precio Costo", "Precio Venta", "En existencia", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(TCatalogo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 138, 676, 125));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Consultar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 9, -1, -1));

        jLabel2.setText("Clave del Producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 70, -1, -1));
        getContentPane().add(TFProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 57, 79, 29));

        jButton1.setText("Regresar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 97, -1, -1));

        ButtonConsultar.setText("Consultar");
        ButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 97, -1, -1));

        ButtonListo.setText("Listo");
        ButtonListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListoActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 274, 71, -1));

        CreditoRB.setText("Credito");
        CreditoRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditoRBActionPerformed(evt);
            }
        });
        getContentPane().add(CreditoRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 274, -1, -1));

        ContadoRB.setText("Contado");
        ContadoRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContadoRBActionPerformed(evt);
            }
        });
        getContentPane().add(ContadoRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 274, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultarActionPerformed
        String id;
        id = TFProducto.getText();
        ConexionDB c = new ConexionDB();
        String sql = "SELECT * FROM Proyecto.Inventario WHERE Clave ="+id;
        c.consultar("Proyecto", "root", "", sql);
        try {
            while (c.datos.next()){
                TCatalogo.setValueAt(c.datos.getInt("Clave"), k, 0);
                TCatalogo.setValueAt(c.datos.getString("Modelo"), k, 1);
                TCatalogo.setValueAt(c.datos.getInt("Serie"), k, 2);
                TCatalogo.setValueAt(c.datos.getString("Descripcion"), k, 3);
                TCatalogo.setValueAt(c.datos.getFloat("PrecioCosto"), k, 4);
                TCatalogo.setValueAt(c.datos.getFloat("PrecioVenta"), k, 5);
                TCatalogo.setValueAt(c.datos.getString("Existencia"), k, 6);
            }
            k++;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se pudo hacer la consulta", "Error", ERROR_MESSAGE);
        } finally {
            c.desconectar();
        }
    }//GEN-LAST:event_ButtonConsultarActionPerformed
        
    private void ButtonListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListoActionPerformed
        total=0;
        for (int j = 0; j < k; j++) {
            Integer cant = Integer.parseInt(TCatalogo.getValueAt(j, 7).toString());
            Integer exis = Integer.parseInt(TCatalogo.getValueAt(j, 6).toString());
            if (exis>=cant) {
                total += Float.parseFloat(TCatalogo.getValueAt(j, 5).toString())*Float.parseFloat(TCatalogo.getValueAt(j, 7).toString());
                if (ContadoRB.isSelected()) {
                    total -= total*0.10;     
                }
                Factura f = new Factura();
                Integer ncant = exis - cant;
                ConexionDB c = new ConexionDB();
                String sql = "UPDATE Proyecto.Inventario SET Existencia = "+ncant+" WHERE Clave = "+TCatalogo.getValueAt(j, 0);
                c.actulizar("Proyecto", "root", "", sql);
                f.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "En el articulo de ID: "+TCatalogo.getValueAt(j, 0)+" exede las existencias", "Informacion", WARNING_MESSAGE);
            } 
        }
    }//GEN-LAST:event_ButtonListoActionPerformed

    private void CreditoRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditoRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreditoRBActionPerformed

    private void ContadoRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContadoRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContadoRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConsultar;
    private javax.swing.JButton ButtonListo;
    private javax.swing.JRadioButton ContadoRB;
    private javax.swing.JRadioButton CreditoRB;
    private javax.swing.JTable TCatalogo;
    private javax.swing.JTextField TFProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
