/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

/**
 *
 * @author magar
 */
public class RegistroClientes extends javax.swing.JFrame {

    /**
     * Creates new form RegistroClientes
     */
    public RegistroClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        TFApPat = new javax.swing.JTextField();
        TFApMat = new javax.swing.JTextField();
        TFRFC = new javax.swing.JTextField();
        TFContrasena = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        ButtonListo = new javax.swing.JButton();
        ButtonRegresar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Constraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 245, 80, -1));

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 79, 80, -1));

        jLabel4.setText("Apellido Paterno");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 117, 80, -1));

        jLabel5.setText("Apellido Materno");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 160, -1, -1));

        jLabel6.setText("RFC");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 204, 80, -1));
        getContentPane().add(TFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 76, 170, -1));
        getContentPane().add(TFApPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 114, 170, -1));
        getContentPane().add(TFApMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 157, 170, -1));
        getContentPane().add(TFRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 201, 170, -1));
        getContentPane().add(TFContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 239, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("Registro Cliente");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 11, -1, -1));

        ButtonListo.setText("Listo");
        ButtonListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListoActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 277, -1, -1));

        ButtonRegresar.setText("Regresar");
        ButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 277, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListoActionPerformed
        ConexionDB d = new ConexionDB();
        String nombre = TFNombre.getText();
        String ApellidoP = TFApPat.getText();
        String ApellidoM = TFApMat.getText();
        String RFC = TFRFC.getText();
        String contrasena = TFContrasena.getText();
        d.singupclientes("Proyecto", "root", "", contrasena, nombre, ApellidoP, ApellidoM, RFC);
        Catalogo cat= new Catalogo();
        cat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonListoActionPerformed

    private void ButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegresarActionPerformed
        ConsultarCliente con= new ConsultarCliente();
        con.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonListo;
    private javax.swing.JButton ButtonRegresar;
    private javax.swing.JTextField TFApMat;
    private javax.swing.JTextField TFApPat;
    private javax.swing.JPasswordField TFContrasena;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTextField TFRFC;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
}
